name: Submit to winget on Release

on:
  release:
    types: [published]

jobs:
  winget:
    runs-on: windows-latest
    steps:
      - name: Submit to winget
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: Natthaphon-SNT.vibeKidbright
          token: ${{ secrets.WINGET_TOKEN }}
